class LevelQuestion {
  final String domain;
  final String difficulty;
  final String prompt;
  final List<String> choices;
  final int answerIndex;

  const LevelQuestion(
    this.domain,
    this.difficulty,
    this.prompt,
    this.choices,
    this.answerIndex,
  );
}

const levelQuestions = <String, List<LevelQuestion>>{
  '국어': [
    LevelQuestion('독서', '기초', '글의 중심 내용을 가장 정확하게 파악하는 방법은?', [
      '반복되는 핵심어와 문단의 중심 문장을 확인한다.',
      '가장 긴 문장만 골라 읽는다.',
      '모르는 단어의 수를 센다.',
      '첫 문장의 표현만 외운다.',
    ], 0),
    LevelQuestion('독서', '기초', '주장을 뒷받침하는 구체적 자료를 무엇이라고 하는가?', [
      '화제',
      '근거',
      '비유',
      '반어',
    ], 1),
    LevelQuestion('문학', '기초', '다음 중 직유법이 사용된 표현은?', [
      '마음에 꽃이 피었다.',
      '시간이 달려간다.',
      '눈이 별처럼 빛난다.',
      '바람이 노래한다.',
    ], 2),
    LevelQuestion('문법', '기초', '다음 중 명사만으로 이루어진 것은?', [
      '학교, 우정, 생각',
      '빠르다, 달리다, 웃다',
      '매우, 곧, 벌써',
      '새, 모든, 어떤',
    ], 0),
    LevelQuestion('어휘', '기초', '“회의 결과를 모두에게 알렸다.”에서 ‘알렸다’와 의미가 가장 가까운 말은?', [
      '숨겼다',
      '통보했다',
      '삭제했다',
      '추측했다',
    ], 1),
    LevelQuestion('문법', '기초', '다음 중 주어가 생략되지 않은 문장은?', [
      '비가 많이 내린다.',
      '지금 출발하자.',
      '숙제를 끝냈다.',
      '참 아름답구나.',
    ], 0),
    LevelQuestion('문학', '핵심', '소설에서 사건을 바라보고 전달하는 위치를 무엇이라고 하는가?', [
      '배경',
      '갈등',
      '시점',
      '복선',
    ], 2),
    LevelQuestion('문학', '핵심', '인물의 내적 갈등에 해당하는 것은?', [
      '두 친구가 서로 다툰다.',
      '가고 싶지만 약속 때문에 망설인다.',
      '마을과 자연환경이 대립한다.',
      '팀과 상대 팀이 경기한다.',
    ], 1),
    LevelQuestion('문법', '핵심', '“새 책이 책상 위에 놓였다.”에서 관형어는?', [
      '새',
      '책이',
      '책상 위에',
      '놓였다',
    ], 0),
    LevelQuestion('문법', '핵심', '다음 중 피동 표현이 사용된 문장은?', [
      '민수가 문을 열었다.',
      '문이 바람에 열렸다.',
      '우리는 운동장을 달렸다.',
      '선생님이 책을 읽었다.',
    ], 1),
    LevelQuestion('독서', '핵심', '두 대상의 공통점과 차이점을 중심으로 설명하는 방식은?', [
      '정의',
      '인과',
      '비교·대조',
      '분류',
    ], 2),
    LevelQuestion('독서', '핵심', '“강수량이 줄었기 때문에 저수지 수위가 낮아졌다.”에 사용된 전개 방식은?', [
      '원인과 결과',
      '시간 순서',
      '문제와 해결',
      '공간 순서',
    ], 0),
    LevelQuestion('문학', '핵심', '“찬란한 슬픔”처럼 모순되는 표현으로 의미를 강조하는 방법은?', [
      '직유',
      '의인',
      '역설',
      '반복',
    ], 2),
    LevelQuestion('쓰기', '핵심', '주장하는 글의 개요를 작성할 때 가장 먼저 정할 것은?', [
      '글씨체',
      '주장과 독자',
      '문장 길이',
      '인용문의 수',
    ], 1),
    LevelQuestion('화법', '핵심', '토의에서 바람직한 참여 태도는?', [
      '상대 발언을 끝까지 듣고 근거로 의견을 말한다.',
      '내 의견과 다르면 즉시 말을 끊는다.',
      '다수 의견을 이유 없이 따른다.',
      '논제와 관계없는 사례를 길게 말한다.',
    ], 0),
    LevelQuestion('독서', '응용', '자료의 신뢰성을 판단하는 기준으로 가장 적절하지 않은 것은?', [
      '출처가 명확한가',
      '작성 시점이 적절한가',
      '근거가 검증 가능한가',
      '제목의 글자 수가 긴가',
    ], 3),
    LevelQuestion('독서', '응용', '글에 드러나지 않은 필자의 관점을 추론할 때 가장 중요한 것은?', [
      '문단 수',
      '근거의 선택과 표현 방식',
      '한자의 개수',
      '문장의 평균 길이',
    ], 1),
    LevelQuestion('문학', '응용', '소설에서 앞에 제시된 단서가 뒤 사건을 암시하는 장치는?', [
      '반전',
      '복선',
      '요약',
      '논평',
    ], 1),
    LevelQuestion('쓰기', '응용', '고쳐쓰기에서 문단 전체의 통일성을 높이는 방법은?', [
      '주제와 관련 없는 문장을 삭제한다.',
      '모든 문장을 더 길게 쓴다.',
      '같은 접속어를 반복한다.',
      '어려운 단어로 모두 바꾼다.',
    ], 0),
    LevelQuestion('매체', '응용', '같은 사건을 다룬 두 기사의 관점 차이를 확인할 때 우선 비교할 것은?', [
      '광고의 위치',
      '제목과 인용한 정보',
      '사진의 해상도',
      '댓글의 개수',
    ], 1),
  ],
  '영어': [
    LevelQuestion('Grammar', '기초', 'I ___ a student. 빈칸에 알맞은 말은?', [
      'am',
      'is',
      'are',
      'be',
    ], 0),
    LevelQuestion('Grammar', '기초', 'She ___ to school yesterday.', [
      'go',
      'goes',
      'went',
      'going',
    ], 2),
    LevelQuestion('Vocabulary', '기초', '“책을 읽다”에 해당하는 표현은?', [
      'write a book',
      'read a book',
      'buy a desk',
      'open a door',
    ], 1),
    LevelQuestion('Grammar', '기초', 'There ___ two apples on the table.', [
      'is',
      'are',
      'was',
      'be',
    ], 1),
    LevelQuestion('Grammar', '기초', 'My brother is taller ___ me.', [
      'at',
      'for',
      'than',
      'from',
    ], 2),
    LevelQuestion('Vocabulary', '기초', '“important”와 의미가 가장 가까운 단어는?', [
      'necessary',
      'tiny',
      'quiet',
      'empty',
    ], 0),
    LevelQuestion('Grammar', '핵심', 'I have lived here ___ three years.', [
      'since',
      'for',
      'during',
      'from',
    ], 1),
    LevelQuestion('Grammar', '핵심', 'The window ___ by Tom yesterday.', [
      'breaks',
      'broke',
      'was broken',
      'is breaking',
    ], 2),
    LevelQuestion(
      'Grammar',
      '핵심',
      'This is the book ___ I borrowed from the library.',
      ['who', 'where', 'that', 'when'],
      2,
    ),
    LevelQuestion(
      'Grammar',
      '핵심',
      'She went to the library ___ study for the test.',
      ['to', 'for', 'so', 'but'],
      0,
    ),
    LevelQuestion(
      'Grammar',
      '핵심',
      '___ exercise regularly is good for your health.',
      ['Do', 'Did', 'Doing', 'Done'],
      2,
    ),
    LevelQuestion(
      'Reading',
      '핵심',
      '“Although it was raining, we continued the game.”의 의미는?',
      ['비가 와서 경기를 취소했다.', '비가 왔지만 경기를 계속했다.', '경기 후에 비가 왔다.', '비가 오기 전에 경기했다.'],
      1,
    ),
    LevelQuestion('Grammar', '핵심', 'If I ___ enough time, I will help you.', [
      'have',
      'had',
      'will have',
      'having',
    ], 0),
    LevelQuestion('Vocabulary', '핵심', '“reduce waste”의 의미로 가장 적절한 것은?', [
      '쓰레기를 분류하다',
      '쓰레기를 줄이다',
      '쓰레기를 태우다',
      '쓰레기를 옮기다',
    ], 1),
    LevelQuestion('Reading', '핵심', '글의 주제를 찾을 때 가장 먼저 확인할 것은?', [
      '반복되는 핵심어와 필자의 요지',
      '모든 단어의 품사',
      '문장마다 사용된 시제',
      '가장 어려운 단어 하나',
    ], 0),
    LevelQuestion('Grammar', '응용', 'By the time we arrived, the movie ___.', [
      'starts',
      'has started',
      'had started',
      'will start',
    ], 2),
    LevelQuestion(
      'Grammar',
      '응용',
      'The teacher made the students ___ the assignment again.',
      ['do', 'to do', 'doing', 'done'],
      0,
    ),
    LevelQuestion(
      'Grammar',
      '응용',
      'Not only Mina but also her friends ___ joining the club.',
      ['is', 'are', 'was', 'be'],
      1,
    ),
    LevelQuestion(
      'Reading',
      '응용',
      '“The plan is practical; nevertheless, it requires more funding.”에서 nevertheless의 역할은?',
      ['원인 제시', '예시 추가', '대조 전환', '시간 순서'],
      2,
    ),
    LevelQuestion('Reading', '응용', '글쓴이가 자료를 인용하는 주된 목적은?', [
      '문장을 길게 만들기 위해',
      '주장의 신뢰성과 설득력을 높이기 위해',
      '새로운 인물을 소개하기 위해',
      '문법 지식을 보여주기 위해',
    ], 1),
  ],
  '수학': [
    LevelQuestion('수와 연산', '기초', 'x + 7 = 15일 때 x의 값은?', [
      '6',
      '7',
      '8',
      '9',
    ], 2),
    LevelQuestion('함수', '기초', '일차함수 y = 2x + 3의 기울기는?', [
      '2',
      '3',
      '-2',
      '-3',
    ], 0),
    LevelQuestion('기하', '기초', '삼각형 세 내각의 합은?', [
      '90°',
      '180°',
      '270°',
      '360°',
    ], 1),
    LevelQuestion('수와 연산', '기초', '3² × 3³의 값은?', ['3⁵', '6⁵', '9⁶', '3⁶'], 0),
    LevelQuestion('확률', '기초', '공정한 주사위를 한 번 던질 때 짝수가 나올 확률은?', [
      '1/6',
      '1/3',
      '1/2',
      '2/3',
    ], 2),
    LevelQuestion('통계', '기초', '2, 4, 6, 8의 평균은?', ['4', '5', '6', '7'], 1),
    LevelQuestion('문자와 식', '핵심', 'x² - 5x + 6을 인수분해한 것은?', [
      '(x-1)(x-6)',
      '(x-2)(x-3)',
      '(x+2)(x+3)',
      '(x-2)(x+3)',
    ], 1),
    LevelQuestion('수와 연산', '핵심', '√50을 가장 간단히 나타낸 것은?', [
      '5√2',
      '10√5',
      '25√2',
      '2√5',
    ], 0),
    LevelQuestion('방정식', '핵심', '2x - 3 > 7의 해는?', [
      'x > 2',
      'x > 5',
      'x < 2',
      'x < 5',
    ], 1),
    LevelQuestion('함수', '핵심', '함수 y = -x + 4의 그래프가 y축과 만나는 점은?', [
      '(0, -1)',
      '(0, 4)',
      '(4, 0)',
      '(-4, 0)',
    ], 1),
    LevelQuestion('기하', '핵심', '반지름이 3인 원의 넓이는?', ['3π', '6π', '9π', '12π'], 2),
    LevelQuestion('수열', '핵심', '등차수열 2, 5, 8, 11, …의 공차는?', [
      '2',
      '3',
      '5',
      '8',
    ], 1),
    LevelQuestion('방정식', '핵심', '연립방정식 x+y=7, x-y=1의 해는?', [
      'x=3, y=4',
      'x=4, y=3',
      'x=5, y=2',
      'x=6, y=1',
    ], 1),
    LevelQuestion('기하', '핵심', '직각삼각형의 두 변의 길이가 3, 4일 때 빗변의 길이는?', [
      '5',
      '6',
      '7',
      '8',
    ], 0),
    LevelQuestion('확률', '핵심', '동전을 두 번 던질 때 모두 앞면이 나올 확률은?', [
      '1/2',
      '1/3',
      '1/4',
      '1/8',
    ], 2),
    LevelQuestion('함수', '응용', '이차함수 y=(x-2)²+1의 꼭짓점은?', [
      '(-2, 1)',
      '(1, 2)',
      '(2, 1)',
      '(2, -1)',
    ], 2),
    LevelQuestion('수열', '응용', '등비수열 3, 6, 12, 24, …의 여섯째 항은?', [
      '48',
      '72',
      '96',
      '192',
    ], 2),
    LevelQuestion('경우의 수', '응용', '서로 다른 4명 중 회장 1명과 부회장 1명을 뽑는 경우의 수는?', [
      '4',
      '6',
      '8',
      '12',
    ], 3),
    LevelQuestion('좌표', '응용', '두 점 (1, 2), (4, 6) 사이의 거리는?', [
      '4',
      '5',
      '6',
      '7',
    ], 1),
    LevelQuestion('미적분 기초', '응용', '함수 f(x)=x²+3x의 x=2에서의 미분계수는?', [
      '4',
      '5',
      '6',
      '7',
    ], 3),
  ],
};
